name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    name: "Update deploy branch"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Get token
      id: get_token
      uses: machine-learning-apps/actions-app-token@master
      with:
        APP_PEM: ${{ secrets.BRASSBOARD_COMMIT_BOT_PEM }}
        APP_ID: ${{ secrets.BRASSBOARD_COMMIT_BOT_ID }}

    - uses: actions/checkout@v5
      with:
        token: ${{ steps.get_token.outputs.app_token }}
        fetch-depth: 0

    - name: Commit to deploy branch
      run: |
        git config --global user.name 'Yichao Yu'
        git config --global user.email 'yuyichao@users.noreply.github.com'
        git status
        git checkout -b deploy
        git status
        git push -f origin deploy
