name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    name: "Update deploy branch"
    runs-on: ubuntu-24.04 # Required for cython3
    strategy:
      fail-fast: false

    steps:
    - name: Get token
      id: get_token
      uses: machine-learning-apps/actions-app-token@master
      with:
        APP_PEM: ${{ secrets.BRASSBOARD_COMMIT_BOT_PEM }}
        APP_ID: ${{ secrets.BRASSBOARD_COMMIT_BOT_ID }}

    - uses: actions/checkout@v4
      with:
        token: ${{ steps.get_token.outputs.app_token }}
        fetch-depth: 0

    - name: Install dependencies
      run: sudo apt-get install cython3 python3-numpy python3-coverage python3-pytest

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Clean
      working-directory: ${{github.workspace}}/build
      run: make clean -j $(nproc)

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make -j $(nproc)

    - name: Update C++ files
      working-directory: ${{github.workspace}}/build
      run: make cython-copyback -j $(nproc)

    - name: Commit to deploy branch
      run: |
        git config --global user.name 'Yichao Yu'
        git config --global user.email 'yuyichao@users.noreply.github.com'
        git status
        git checkout -b deploy
        git add .
        git status
        git commit -m 'Deploy sources'
        git push -f origin deploy
