name: Build and Test

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build and Test (${{matrix.BUILD_TYPE}} build)"
    runs-on: ubuntu-24.04 # Required for cython3
    strategy:
      fail-fast: false
      matrix:
        BUILD_TYPE: [ Release, Debug ]
    env:
      CXXFLAGS_COV: -fprofile-arcs -ftest-coverage

    steps:
    - uses: actions/checkout@v5

    - name: Install dependencies
      run: sudo apt-get install python3-numpy python3-pytest

    - name: Configure CMake
      run: CXXFLAGS+=" ${CXXFLAGS_COV}" cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}} -j $(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.BUILD_TYPE}} --output-on-failure -j $(nproc)

    - name: Test (info)
      working-directory: ${{github.workspace}}/build
      run: BB_LOG=info ctest -C ${{matrix.BUILD_TYPE}} --output-on-failure -j $(nproc) -R test/python/test_utils

    - name: Test (debug)
      working-directory: ${{github.workspace}}/build
      run: BB_LOG=debug ctest -C ${{matrix.BUILD_TYPE}} --output-on-failure -j $(nproc) -R test/python/test_utils

    - name: Upload coverage
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
